### ISSUE TITLE
Outputs do not have coordinate systems for 3 tools

### ISSUE THREAD

**Issue by Hornbydd** [jblindsay/whitebox-tools#79] opened 2020-03-04 10:24 UTC
@jblindsay, I did a little testing of some tools and these ones all came out as "offenders" in that the raster output they produce do not have an assigned coordinate system.

- vector polygons to raster
- vector points to raster
- vector lines to raster

I tested a few of the tools that take shapefiles as inputs and create shapefiles as outputs they were all OK.

**Comment by jblindsay** [comment] 2020-03-04 13:28
@Hornbydd This [change](https://github.com/jblindsay/whitebox-tools/commit/11f0c4f911018f301da2e0076b7ee4d50dcdd5a4#diff-e12f53fb4260930de2b0d65a26dbf1c0) was made four days ago. The current version of these tools in the repository should preserve the projection. I'll close this now but if you find any issues during testing, please feel free to re-open. 

I will say this about projection issues with WhiteboxTools though. Dealing with projections from diverse data sets (vector shapefiles, rasters of varying formats, LAS files) is extremely complex and challenging. Other projects deal with the complexities of managing projection information in the diverse ways that data formats require by using specialized libraries (e.g. GDAL, Proj). I cannot use this same approach, for various design reasons, in WhiteboxTools. And as such, the only way to truly replicate this is to re-write all of the functionality of these libraries. I have no interest in doing that...I am just a one-man show here and there are limitations to what I can do. With WhiteboxTools, I am aiming to provide a solid and capable spatial data analysis library. It is not a full-blown GIS and can never be. This is usually quite simple for tools that take in data in one format and output data in the same format, e.g. a vector analysis tool where the input is guaranteed to be a shapefile and so to is the output. I simply need to copy the projection information into the output file. However, projection issues come to a front for tools where the inputs and outputs are of different formats. For example, when a LAS file is interpolated to a raster. Even raster-input-to-raster-output is challenging because every raster format stores projection information in different ways (most complex of all is the GeoTIFF format). In these situations, you need to have proper means of dealing with projections, which I do not have.

The thing that you need to keep in mind here is this, **there is no layer below WhiteboxTools**. Other geospatial software is built on a 'stack' of common software to handle basic things like reading/writing different data formats, handling projections, coping with the extreme complexity of vector topology. However, because of the desire to make WBT entirely isolated (i.e. it is a stand-alone that does not require other software on the users machine) basically all of these functionalities need to be programmed into the project. And when I say they need to be programmed, it's just me doing that. It may not be obvious to the outside world here, but WhiteboxTools is a one-man show. I've written everything, from the lowest level GeoTIFF reader/writer, to the highest level D8 flow accumulation tool and everything in between. I have limited bandwidth, particularly because WBT is not my full time job. While I certainly do appreciate users telling me when they encounter bugs or unexpected behaviour, I do need to pick and choose my battles. I know that WBT doesn't do as sophisticated a job of handling projection information as other geospatial software does. But I simply don't have the bandwidth to re-write all of Proj into Rust. I would like to spend as much time as possible writing new and interesting spatial analysis tools. To do so requires me to do some basic things as well (e.g. reading/writing different data formats). But ultimately this was the reason that I stopped hacking on Whitebox GAT as well...in that case I had to spend so much effort trying to create a full GIS user-interface. I eventually go to the state where I thought this is nuts because there are GIS out there that can be used to visualize rasters/vectors and to make pretty maps, but I am spending a tremendous effort in enabling these features in WBGAT, again as a one-man show. With WBT, I decided early on that I didn't want to spend any more time working on front-end issues, instead creating the tools in such a way that people can use whatever front-end they like. I still have to deal with the low-level coding issues like this however. The challenge for me is to find the right balance in which I can focus on the stuff that I'm in this for (creating spatial analysis tools) without having to spend my life chasing issues with the low-level stuff. It's tough. Anyhow, I'm sorry for the rant and I hope that you don't interpret this as my being ungrateful for your efforts in trying to improve WBT, because I am truly grateful for your efforts.

**Closed** 2020-03-04 13:28 UTC

**Comment by Hornbydd** [comment] 2020-03-04 14:47
@jblindsay  I totally understand and I don't see your reply as a rant, it's a honest appraisal of how WBT is being developed and hopefully others read.  I understand it's a one man show, for me RivEX has been 8 years in development and still evolving although I fear the writing is on the wall when ESRI retire ArcMap...

I've just caught up with my emails from you and @giswqs  and its what I thought, a short delay in code tweaks/bug fixes before they cascade throughout your systems, which as you say can be a time consume tasks.

I'm accessing WBT principally through the python toolbox, I prefer that as it's one download and all I have to do is unzip it, nice and easy and provides a user friendly interface in the ArcMap environment!

I feel I can best support you by my testing/use of the tools and logging any issues but now realise that at some point you need to eat, sleep and work and not expect an immediate resolution.  If only you could clone yourself... ;)

**Comment by giswqs** [comment] 2020-03-04 18:31
John, I just want to let you know that I really appreciate and admire the work you do! And I am sure numerous GIS users benefit from WBT. I don't know how you manage to do this, but I could not imagine developing such an amazing library from scratch, even it were my full-time job. You must have sacrificed numerous weekend hours and family time on this. As a one-man show, it is impossible to code all the I/O stuff from scratch without relying on third-party libraries (e.g., GDAL). Users can utilize other GIS libraries and packages (e.g., QGIS, ArcGIS) to handle data format conversion and projection issues if needed. I think the numerous advanced geospatial analysis tools in WBT (but not available in other full-blown GIS ) are what make WBT unique and powerful!!

**Comment by jblindsay** [comment] 2020-03-06 13:47
@Hornbydd Yes, that's what I need, a clone! Anyhow, your testing efforts have already significantly improved WBT so I'd encourage you to carry on with them. @giswqs I truly appreciate such kind words from someone that I also admire. Your advocacy for WBT has been tremendous for the project and your efforts on the ArcGIS front-end and Python API are absolutely essential. Much gratitude is sent to both of you.
