### ISSUE TITLE
Rho8 Pointer algorithm gives slightly different results each time

### ISSUE THREAD

**Issue by csmemoe-aquaveo** [jblindsay/whitebox-tools#347] opened 2023-05-10 06:44 UTC
## Expected behavior and actual behavior

I would expect the same results when running the Rho8Pointer Whitebox tool multiple times on the same raster, but I get slightly different results.

## Steps to reproduce the problem

1. Compile and run the Whitebox runner from the repository or any other toolbox that can be used to run a Whitebox tool.  Or you can use the command line interface. I am running from Python but I have also tried this using the Whitebox runner.
2. Bring up the Rho8Pointer tool.
3. Use the following file as the input raster (other rasters probably give similar results, but I haven't tried them): https://file.io/Oq4QyXi4nujC
4. Define an output raster filename such as "rc_elev_flow_ptr_1.tif"
5. Accept any other default values and run the tool.
6. Run the tool again with the same settings except change the output raster filename to "rc_elev_flow_ptr_2.tif".
7. Bring the 2 generated flow accumulation rasters into your favorite raster viewer, such as QGIS.
8. Toggle between the two rasters or use a raster calculator to compute the difference between the output rasters.
9. Note that there are some minor differences.  These differences do not have a huge impact on the flow locations and the resulting flow accumulation rasters, but I would expect the same input raster to give the same output raster for this tool and other tools.  I was able to achieve the same flow pointer and accumulation rasters using the FlowAccumulationFullWorkflow tool.  Maybe the parallelization of the flow direction algorithm makes this so it's not possible though.

## Operating system

Microsoft Windows 10 Pro, Version 10.0.19044 Build 19044, 64 bit

## Whitebox version

Version 2.3, built from master on April 3, 2023

**Comment by jblindsay** [comment] 2023-05-10 10:38
The Rho8 algorithm is inherently stochastic based on the description first provided in the original Fairfield and Leymarie (1991) article. Therefore, each run will naturally produce slightly different results because of the in-built random parameter. If you would like deterministic flow path modelling, I suggest using any of the other available flow algorithms in Whitebox. The D8 algorithm would be the deterministic equivalent to Rho8. The trade off provided by Rho8 is that it has more accurate flow directions in the aggregate (i.e. for the whole raster rather than for any individual grid cell) but that each run will produce a different result. I'm therefore closing this issue, since this is a feature and not a bug but please feel free to reopen it if there is something that I am missing.

**Closed by jblindsay** 2023-05-10 10:38 UTC

**Comment by csmemoe-aquaveo** [comment] 2023-05-10 16:11
I understand, I had not looked at the source code or read the article about the Rho8 algorithm.  Maybe I will do that next time.  I just have liked using the Rho8 algorithm because it seems to give "smoother" results for the stream locations than regular D8 algorithm gave.
