### ISSUE TITLE
Watershed tool

### ISSUE THREAD

**Issue by vangtk** [jblindsay/whitebox-tools#59] opened 2019-11-26 03:44 UTC
I seem to be running into an issue with the watershed tool (implemented in both R and QGIS). It seems to be stuck in a loop and won't write out the raster file. I swung back to v0.14 and its working in the older versions. Just thought I'd check in and see if there was an issue.

Thanks for the awesome tool! Its made huge dividends in my MA research.

**Comment by jblindsay** [comment] 2019-11-26 11:40
@vangtk Thank you for reporting this issue. Would you mind printing the output of the tool, including any printed command-line arguments? What are the data inputs? I know that there has been a change since 0.14.1 in the behaviour of this tool where it takes pour points in as a shapefile rather than raster. Could that be the issue you are having?

**Comment by jblindsay** [comment] 2020-02-14 20:12
@vangtk Are you able to send me the sample data that you have encountered this issue on? I have just updated the Watershed tool and did not encounter any similar issue during testing.

**Comment by jblindsay** [comment] 2020-07-24 15:05
I still have not been able to recreate this issue and so I am closing the ticket. If you are able to share the data that reproduces this issue with me then I will re-open it.

**Closed by jblindsay** 2020-07-24 15:05 UTC
Labels: bug
