### ISSUE TITLE
wbt 2.03: mean_curvature and local_quadratic_regression not available

### ISSUE THREAD

**Issue by CarlosGrohmann** [jblindsay/whitebox-tools#219] opened 2022-01-11 16:38 UTC
Hi.

just tried to calculate some LSP, and noticed that `mean_curvature` and `local_quadratic_regression` were not available. Checking the code here I see `mean_curvature` in the terrain_analysis dir and `local_quadratic_regression` in the plugins dir. 

here is the error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-19-495b6d5d2409> in <module>
     15 for w in [3]: #,5,7,9,11,13,15,17,19,21]:
     16     out_wood = f'wood_{w}x{w}'
---> 17     wbt.local_quadratic_regression(dem=dem, output=out_wood, filter=w)
     18 

AttributeError: 'WhiteboxTools' object has no attribute 'local_quadratic_regression'
```

I installed WBT in Linux using pip. Should I try to compile it? 

thanks

**Comment by jblindsay** [comment] 2022-01-12 21:42
Hi Carlos,

Both the MeanCurvature tool and the LocalQuadraticRegression tool are currently on the development branch but not yet in the public release. We're hoping to release a new version of the WBT open core sometime this month, and so it shouldn't be too long before you can get your hands on these new tools. At this point, I just need to write the documentation for all the new tools that we've added, but that may take a bit of time. Other related things that may interest you: I have just committed changes to the aspect, slope, tangential curv, plan curv, and profile curv tools that update the algorithm to using the more robust Florinsky (2016) 3rd order bivariate polynomial method based on a local 5x5. These tools use this method for DEM with projected CRS and for those in geographic coordinates, I have updated the tools to use the method for calculating curvatures on a sphere, also described by Florinsy (2016). This is a huge improvement for WBT, as you know! In addition, I've just added the code for new Gaussian curvature, minimal and maximal curvature tools. And just a little heads-up for you, we're also going to be announcing soon the addition of eight new curvature tools that use these same improved robust algorithms to the WBT DEM Extension, including rotor, unsphericity, difference curvature, accumulation curvature, ring curvature, vertical and horizontal excess curvatures, and generating function. We're pretty excited!

**Closed by jblindsay** 2022-01-12 21:42 UTC

**Comment by CarlosGrohmann** [comment] 2022-01-14 20:20
Hi John

Lots of great news! I'm looking forward to test those news tools! 

BTW, what do you think of a multi-scale measurement of curvature? 

Carlos

**Comment by jblindsay** [comment] 2022-01-14 20:56
Yes indeed, plenty of good things coming down the line. My PhD student, Dan Newman, just added a new multi-scale curvature (among other surface morphology parameters) tool called [GaussianScaleSpace](https://github.com/jblindsay/whitebox-tools/blob/master/whitebox-plugins/src/gaussian_scale_space/main.rs). It works really well.

**Comment by CarlosGrohmann** [comment] 2022-01-15 23:01
Fantastic! I have to check the reference paper. 

I checked the code and it resamples to DEM at the desired scales, calculates LSPs and then use z-scores for the output. DO you think the results will be much different than calculating the LSPs from the original DEM with a larger window (using local quadratic) and then doing the same z-score procedure?

**Comment by dnewma02** [comment] 2022-01-17 03:02
Hello Carlos,

Unfortunately, the Gaussian scale-space paper John mentioned is still in review. That tool also outputs the LSP value as well as the z-score transformed value and 'optimal scale'. It only uses the z-scores to perform the scale selection or 'optimization'. 

Aside from fact that the slowness of the local quadratic method can hinder the range of scales you evaluate, I believe the Gauss function's sigma parameter gives far more control over the output that does the window size. I have found that the local quadratic method tends to converge on a spatial pattern regardless of the window size parameter, and is becomes a poorer representation of the surface it is modelling as scale increases. I believe it is due to the local nature of the measurement and the fixed degrees of freedom of a 2-d quadratic model respectively. On the other hand, Gaussian scaling uses the same basic method of measuring local derivatives (a fixed 3x3 local quadratic function), but achieves scaling by removing detail from the terrain. This separates scaling from measurement (which is local by definition for derivatives). 

That said, I don't see any reason why applying the z-score procedure can't be done. I'd expect the results to be very similar at smaller scales. However, I'd expect the results would provide less information at larger scales. John and I recently wrote an open source paper that details some of my experimentation on the subject (https://www.researchgate.net/publication/357539447_Evaluating_Scaling_Frameworks_for_Multiscale_Geomorphometric_Analysis). I think figures 2 and 6 should explain my opinion more concisely.

**Comment by jblindsay** [comment] 2022-01-17 08:12
Just to add to what Dan replied Carlos, the rationale for using the z-score procedure for scaling is that as you explore broader scales, the absolute values of many land surface parameters (LSPs) tend towards zero. However, with respect to identifying characteristic scales at a site, to create heterogeneous scale maps, two things are important: 1) we are interested not in identifying the scale at which the absolute parameter value achieves its maximum, but rather when it achieves its most deviated value relative to the overall spatial distribution, and 2) if LSP values tend towards smaller and smaller values at larger scales, a heterogeneous scale map of the LSP needs to standardize the units of the parameter in order to provide a continuous and smooth surface. There is no doubt based on our experiments with it that using the z-score to identify local characteristic scales provides a different, and in many ways more interesting, result than using the original LSP values; in particular, it allows for identification of 'interesting' features at broader scales, where the overall magnitude and range of LSP values would be small relative to their values at more localized scales. I hope that helps to answer your question.

**Comment by CarlosGrohmann** [comment] 2022-01-17 17:10
Thanks so much for the replies! I have two of Dan's papers with me (Geosciences 2018, Geomatics 2022) to read. I asked about using local quadratic because it was an old idea that I never tested. I'm sure your approach is more robust. I'll keep an eye on the repo for the next release!

**Comment by trchudley** [comment] 2022-08-03 20:23
Hi @jblindsay,

Thanks for all your work on WBT. I've also encountered Carlos' error with `local_quadratic_regression` not being available:

```python
wbt.local_quadratic_regression(
    'input_dem.tif', 
    'quadratic_output.tif', 
    filter=3, 
)
```
```
thread 'main' panicked at 'Unrecognized tool name LocalQuadraticRegression.', whitebox-tools-app/src/main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My installation was compiled from the current master branch (reporting v2.1.0). Am I correct in assuming that these tools are yet to make it into the public release? If so, can you recommend which of the development branches I could compile to gain access? 

Cheers,
Tom
