### ISSUE TITLE
Stream Network tools not running

### ISSUE THREAD

**Issue by draconigae** [jblindsay/whitebox-tools#4] opened 2018-05-23 17:34 UTC
When running any of the 'Stream Network' tools (e.g. long_profile, length_of_upstream_channels, etc.) I receive the following error:

thread 'main' panicked at 'Colour map not present in Paletted TIFF.', src\main.rs:49:21

Python call back: 
.\whitebox_tools.exe --run="Longprofile" --wd="E:\Burnett_2018_Projects\End_of_Fish\Stream_Delin\" --d8_pntr='hja_recon_v10_d8recon2_d8pntr.tif' --streams='hja_recon_v10_d8recon2_d8strm.tif' --dem='hja_recon_v10_d8recon2.tif' --output='hja_recon_v10_d8recon2_d8profile.html' -v

Workflow:
input a custom DEM
d8_pntr is output from 'flow_accumulation_full_workflow'
streams is output from 'extract_streams' and based on 'd8_flow_accum' from 'flow_accumulation_full_workflow'

Notes:
d8_pntr and d8_flow_accum rasters appear normal in GIS

System: Windows 10 x64
Ram: 64 GB
Python version: 3.6
WBT Version: 0.7

**Comment by jblindsay** [comment] 2018-05-24 12:31
@draconigae Thank you for submitting this issue and for providing all of the details that I need to figure out what happened to your code. I certainly appreciate that! I think that the issue is related to the fact that when a tool saves raster data using a Categorical format, if the data are saved as a GeoTIFF, the reader will expect it to be Paletted, i.e. to store a colour table. However, since these data do not in fact store additional colour information, this is not the case and the subsequent read operation will fail. A simple fix would be to store the data with Continuous photometric interpretation, even when the tool says that it should be Categorical. I've committed a fix along those lines [here](https://github.com/jblindsay/whitebox-tools/blob/a4863ed95244da89679fcb0fb7c0d1acc35fac53/src/raster/geotiff/mod.rs#L1045). I'm hoping to release version 0.8 in the next couple of days, so you I would appreciate when I do if you could re-test it with your workflow and confirm that this fixed the issue.

**Closed** 2019-10-04 14:59 UTC

**Comment by jonschwenk** [comment] 2020-06-12 21:56
Same issue here. v 0.8.0. My workaround was to re-save the wbt output grids as floats.
