### ISSUE TITLE
elevation_above_stream_euclidean producing empty tif

### ISSUE THREAD

**Issue by erikafreeman** [jblindsay/whitebox-tools#35] opened 2019-05-08 15:20 UTC
I have a script that uses both the elevation_above_stream_euclidean and the elevation_above_stream tools. The inputs are the same. 

These are the lines of code: 

wbt.elevation_above_stream(dem= path+name+tif, streams= name + '_'+ n  + '_streams.tif', output= name + '_' + n + 'HAND.tif')

wbt.elevation_above_stream_euclidean(dem= path+name+tif, streams=name + '_' + n  + '_streams.tif', output= name + '_' + n + 'HANDe.tif')

However, the wbt.elevation_above_stream_euclidean produces an empty .tif without throwing an error.

**Comment by erikafreeman** [comment] 2019-05-08 15:21
and I forgot to mention that the wbt.elevation_above_stream line works.

**Comment by jblindsay** [comment] 2019-05-25 19:08
@erikafreeman I just tested this tool on a sample DEM that I had and it worked as expected. Can you share your DEM and stream file so that I can try to replicate your issue?

**Comment by jblindsay** [comment] 2020-07-24 14:33
I suspect that this issue was related to the GeoTIFF reader/writer and has now been resolved and so I am closing it. My testing with the tool does not show any issue. If you encounter any further problems, please feel free to re-open it.

**Closed by jblindsay** 2020-07-24 14:33 UTC
Labels: bug

**Comment by Atreyagaurav** [comment] 2023-09-03 23:44
The problem is not from GeoTIFF, but from the algorithm. 

I've mentioned it here: https://github.com/jblindsay/whitebox-tools/issues/245

Maybe you ignored it thinking it's the issue from ourside the whitebox tools.

The problem is, the tool masks the value if "streams" raster has no_data values on it. For the streams file normally generated, it's fine as it has 1 for streams and 0 for others, but if you've run it through the ordering algorithms, then it'll have numbers for streams and no_data for others, in that case the algorithm will only output values on the streams and have mostly empty output. 

You can find the fix that I purposed at that time on the linked issue. But the code seems to have changed since then, I can open up a pull request with a new code if I can figure out what to change on the new one again.

Here are some files that you can use to replicate it in the latest version. https://drive.google.com/drive/folders/16BPmX8jI8xJGFsKIHcQjioJ2b5Qjx4Ya?usp=sharing
