### ISSUE TITLE
Shapefile geometry type support

### ISSUE THREAD

**Issue by lahm3d** [jblindsay/whitebox-tools#34] opened 2019-04-24 15:07 UTC
Not sure, if this is an issue or user error, but I am trying to use WBT clip tool to extract streams (polyline) inside a watershed (polygon) and I get the following error:

```
Reading data...
thread 'main' panicked at 'Unrecognized ShapeType', src\vector\shapefile\geometry.rs:483:18
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I checked the geometry types of my datasets: watershed = 'Polygon' and streams = 'LineString', however, after looking through geometry.rs I see no reference to LineString. Is there something I'm missing here?

Additional info. the watershed originally a DEM that is polygonized using rasterio & shapely, and finally written out using geopandas as `ESRI Shapefile`. And the streams are NHD projected streams. Here is the snippet:

```
with rasterio.open("D:/dem.tif") as ds_dem:
    arr_dem = ds_dem.read(1)

arr_dem[arr_dem > 0] = 100
mask = arr_dem == 100

results = (
    {'properties': {'raster_val': v}, 'geometry': s}
    for i, (s, v)
    in enumerate(
    shapes(arr_dem, mask=mask, transform=ds_dem.transform)))

poly = list(results)
poly_df = gpd.GeoDataFrame.from_features(poly)
poly_df.crs = in_crs
poly_df.to_file("D:/watershed_boundary.shp")

streams     = "D:/NHD_streams.shp"
boundary    = "D:/watershed_boundary.shp"
output      = "D:/clipped_streams.shp"
wbt.clip(streams, tmp, output)
```

**Comment by jblindsay** [comment] 2019-04-24 15:13
WhiteboxTools has its own custom implementation of a Shapefile encoder/decoder and it follows the published 1998 [Shapefile Whitepaper](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf) very closely. The various supported Shape Types of a Shapefile are provided on page 4 of the linked document. There is no `LineString` Shape Type. I suspect that it would be the same, in terms of how it is being stored, as a `PolyLine`. The problem is, there is no numerical value provided for the `LineString` alias. It would seem that either shapely or geopandas are implementing their own modified version of a Shapefile. I'm not sure what to do about that. However, I would suggest that if you are able to convert it to a proper `PolyLine`, that is likely the easiest solution.

**Comment by jblindsay** [comment] 2019-04-24 15:18
@lahm3d Is it possible that you can forward me your stream shapefile so that I can take a look at its internal structure? Most importantly, I need to know what numeric value they are placing in the ShapeType part of the file to indicate the `LineString` type.

**Comment by lahm3d** [comment] 2019-04-24 15:44
Thanks @jblindsay. Of course, here is the [stream shapfile](https://drive.google.com/file/d/1EJO6rMqaypjPqrHV3kPu9PSSipaOz93p/view?usp=sharing).

I tried, unsuccessfully, to modify the the stream shapefile's schema using fiona, but that threw the following error:

`fiona.errors.UnSupportedGeometryTypeError: 'PolyLine'`

I will also try explicitly specifying my output schema and geometry type and see if that fixes the geometry issue. Thanks again!

**Comment by jblindsay** [comment] 2019-04-24 18:17
Thank you for sending me your file. This was very helpful for diagnosing the issue. I've come to realize that LineString25D (the ShapeType that QGIS provides for your file) is just an alias for PolyLineZ. The actual problem with reading the file was on my part. It turns out that for a PolyLineZ, although there are Z and M parts to each geometry, the M parts are optional. Your file does not use the optional M parts. Admittedly, I've never seen a file do this before; however, the Shapefile Whitepaper makes it clear that this is a valid form of the file format. As such, I've added the ability to leave out the M component of PolyLineZ, PolygonZ, and MultiPointZ Shapefile Geometries and have submitted a fix to the repo. The fix will be available in the next release of the software, which I am hoping to release sometime in the next week. If you cannot wait for this, you may consider compiling from source. I'm closing the issue now but please feel free to re-open if you encounter further problems with this issue. Thank you again for not only reporting the issue but for also providing enough information to diagnose the problem. Much appreciated!

**Closed by jblindsay** 2019-04-24 18:17 UTC

**Comment by lahm3d** [comment] 2019-04-29 15:59
Belated thanks @jblindsay. I was able to compile and successfully test the clip function. And thank you very much for your continued help and support!

**Comment by jblindsay** [comment] 2019-04-29 21:47
@lahm3d Glad to hear that it worked for you and thanks again for reporting the issue.
