### ISSUE TITLE
--fill argument in BreachDepressionsLeastCost not honored

### ISSUE THREAD

**Issue by kmsampson** [jblindsay/whitebox-tools#127] opened 2020-11-17 05:54 UTC
In testing of the BreachDepressionsLeastCost tool, (via Python API and whitebox_tools.exe), I have found that regardless of whether or not the `--fill` parameter is provided, all non-breached depressions are filled. The results of running the tool with and without the `--fill` parameter are indeed different from each other, but both raise (fill) elevation values in the output when compared to the input DEM. If I interpret the documentation correctly, the intention of the `--fill` parameter is to allow a user to perform a 'breach-only' run of the Breach Depressions (Least Cost) tool, which is what I am trying to do, but even without placing any limits on the breach cost or distance, the result contains filled areas. Let me know if you need any example files.

**Comment by jfbourdon** [comment] 2021-03-23 14:19
As I often use this tool I wanted to check but I can't replicate your issue. Without the `--fill` parameter, unbreached depressions really remain untouched. Are you testing with the latest release (1.4.0) ?

**Comment by Afrancioni** [comment] 2021-08-09 15:46
Similar to @jfbourdon I also tested this issue with similar results. Without the --fill parameter, unbreached depressions in my test DEM remained untouched. I have also been testing with the latest stable release (1.5.0). I am going to close this issue as I can replicate it. If you are still experiencing this issue, I can re-open and look into it further.

**Closed by Afrancioni** 2021-08-09 15:46 UTC

**Comment by jfbourdon** [comment] 2021-09-04 01:56
Now that I started using the Python API a bit more, I'm pretty sure it was caused by the fact that the fill parameter is set to `True` by default in the Python API but is set to `false` when using WBT in command-line. See #194 for the details.
