### ISSUE TITLE
Whitebox 2.4.0 MultiscaleTopographicPositionImage - hillshade no longer optional?

### ISSUE THREAD

**Issue by lauren-obrien** [jblindsay/whitebox-tools#423] opened 2024-07-30 23:37 UTC
**Environment:** R.4.4.0, Whitebox R frontend v2.4.0, Whitebox tools 2.4.0, Windows 10
**Hardware:** Dell Precision 5570, i7, 64GB RAM

**Problem:**
- Tool MultiscaleTopographicPositionImage was failing with error `thread 'main' panicked at whitebox-tools-app\src\main.rs:72:21:
The input files must have the same number of rows and columns and spatial extent.`
- gdalinfo confirms the inputs do have the same size and extent (as they should; they were all directly output from tool MaxElevationDeviation, from the same input file)
- Issue was first observed with large lidar files  (22320 x 22320 cells, 2m size, EPSG:2193). Subset to small area in case its a hidden memory issue, no change. Built reprex below with R package 'terra' demo DEM (90 x 95 cells, 0.008333333 degrees, EPSG:4326), no change
- added a hillshade to the reprex, tool ran successfully
- Issue replicates on pure command line, so R or the R wrapper package don't appear to be at fault
- Documentation still indicates `--hillshade` is an optional parameter. I prefer that, as my habit is to add surfaces like this to a GIS with an existing hillshade, and make them slightly transparent to get a similar visual effect.
- Tried supplying an all-NA, all-0, or all-255 raster to `--hillshade` as a workaround but that didn't work - all-black outputs.
- I can rescale the devmax rasters in R or GDAL to build an MSTPI image myself, but that's extra work.
- Is the documentation at fault, or the tool?

**Reprex:**
```
library(terra)
library(whitebox)

f <- system.file("ex/elev.tif", package="terra")
working_dir <- tempdir()

# devmax x3 
wbt_max_elevation_deviation(
  f,
  out_mag   = file.path(working_dir,'f_DEVmax_mag_local.tif'),
  out_scale =  file.path(working_dir, 'f_DEVmax_scale_local.tif'),
  min_scale = 1L,
  max_scale = 10L,
  step      = 2L,
  verbose_mode = FALSE
)

wbt_max_elevation_deviation(
  f,
  out_mag   = file.path(working_dir,'f_DEVmax_mag_interm.tif'),
  out_scale =  file.path(working_dir, 'f_DEVmax_scale_interm.tif'),
  min_scale = 11L,
  max_scale = 30L,
  step      = 5L,
  verbose_mode = FALSE
)

wbt_max_elevation_deviation(
  f,
  out_mag   = file.path(working_dir,'f_DEVmax_mag_region.tif'),
  out_scale =  file.path(working_dir, 'f_DEVmax_scale_region.tif'),
  min_scale = 31L,
  max_scale = 50L,
  step      = 5L,
  verbose_mode = FALSE
)

devmax <- rast(file.path(working_dir, 
                         paste0('f_DEVmax_mag_',
                                c('local', 'interm', 'region'), 
                                '.tif')))
# they read in and stack correctly so have the same dimensions and extent
plot(devmax)   # looks fine            

# error:
wbt_multiscale_topographic_position_image(
  local  = file.path(working_dir, 'f_DEVmax_mag_local.tif'),
  meso   = file.path(working_dir, 'f_DEVmax_mag_interm.tif'),
  broad  = file.path(working_dir, 'f_DEVmax_mag_region.tif'),
  output = file.path(working_dir, 'f_MS_TPI_2m.tif'),
  lightness = 1.2,
  verbose_mode = TRUE
)

# include a hillshade:
slp <- terrain(r, v='slope', unit = 'radians')
asp <- terrain(r, v = 'aspect', unit = 'radians')
hs <- shade(slp, asp, normalize = TRUE)
writeRaster(hs, file.path(working_dir, 'hs.tif'))

# successful:
wbt_multiscale_topographic_position_image(
  local  = file.path(working_dir, 'f_DEVmax_mag_local.tif'),
  meso   = file.path(working_dir, 'f_DEVmax_mag_interm.tif'),
  broad  = file.path(working_dir, 'f_DEVmax_mag_region.tif'),
  output = file.path(working_dir, 'f_MS_TPI_hs_2m.tif'),
  hillshade = file.path(working_dir, 'hs.tif'),
  lightness = 1.2,
  verbose_mode = TRUE
) 
```

**Comment by jblindsay** [comment] 2024-08-07 16:08
I think that this might be an issue with the R-frontend because it works as expected in the Whitebox Runner:

![image](https://github.com/user-attachments/assets/3d1eca57-0e54-428b-85fe-7514d0d4dd41)

As you can see in the image above, I did not specify a hillshade image and the tool worked correctly. You may need to raise an issue with the Whitebox R frontend repo instead.

**Comment by brownag** [comment] 2024-08-07 16:34
I can confirm that the error occurs in the command line when `--hillshade` argument is not specified. 

The issue is not limited to the R frontend, as @lauren-obrien pointed out.
```
$ "C:\PROGRA~1\WHITEB~1\WBT\WHITEB~2.EXE" --run=MultiscaleTopographicPositionImage  --local="C:\Users\ANDREW~1.BRO\AppData\Local\Temp\RtmpmgXmUB/f_DEVmax_mag_local.tif" --meso="C:\Users\ANDREW~1.BRO\AppData\Local\Temp\RtmpmgXmUB/f_DEVmax_mag_interm.tif" --broad="C:\Users\ANDREW~1.BRO\AppData\Local\Temp\RtmpmgXmUB/f_DEVmax_mag_region.tif" --output="C:\Users\ANDREW~1.BRO\AppData\Local\Temp\RtmpmgXmUB/f_MS_TPI_2m.tif" --lightness=1.2 -v
*************************************************
* Welcome to MultiscaleTopographicPositionImage *
* Powered by WhiteboxTools                      *
* www.whiteboxgeo.com                           *
*************************************************
Reading broad-scale DEV data...
Reading meso-scale DEV data...
Reading local-scale DEV data...
thread 'main' panicked at 'The input files must have the same number of rows and columns and spatial extent.', whitebox-tools-app\src\main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jblindsay** [comment] 2024-08-07 17:27
@brownag You're right! I'll look further into this then.

**Comment by jblindsay** [comment] 2024-08-07 17:43
Okay, I just identified the problem. There was a missing set of brackets around a compound condition in an if statement. I'm not sure why I have never noticed this issue previously but I thank you @lauren-obrien for pointing it out. The fix will be part of the next public release whenever that occurs. In the meantime, feel free to build from source code.

**Closed by jblindsay** 2024-08-07 17:43 UTC
