### ISSUE TITLE
Projection Issue - Low Priority

### ISSUE THREAD

**Issue by draconigae** [jblindsay/whitebox-tools#6] opened 2018-05-25 20:36 UTC
DEM Geotiffs with NAD 83 UTM Zone 10N projection produce derivative geotiffs with grids in the same coordinate system, but the metadata has changed to GCS NAD 1983 with decimal degree units, which causes difficulties in GIS.

**Comment by jblindsay** [comment] 2018-09-04 15:31
@draconigae So I'm having a hard time understanding exactly what the issue is here. You say that the derivative grids have the same coordinate system but then that the metadata has changed. Are you saying that the coordinate system has changed but that other grid characteristics (e.g. the number of rows and columns) has stayed the same? I'm just trying to clarify.

**Comment by jblindsay** [comment] 2018-12-29 15:55
I believe that the [recently committed](https://github.com/jblindsay/whitebox-tools/commit/9ffeb39cc87da5363777c6595ffc452df8f6dd23) updates to the GeoTIFF reader/writer will correct this issue. If a TIFF is used as the input to a tool and a TIFF is also specified as the output, WhiteboxTools now simply copies the georef tags from input to output rasters.

**Closed by jblindsay** 2018-12-29 15:55 UTC
