### ISSUE TITLE
LidarTINGridding Batch Processing in QGIS always crashes

### ISSUE THREAD

**Issue by BrianMoynihan** [jblindsay/whitebox-tools#217] opened 2022-01-04 19:37 UTC
Trying to run LidarTINGridding in batch mode (inside or outside of graphical model builder) will lead to QGIS crashing after the first input.  A raster will be produced from the first dataset only, which defeats the whole point of batch processing.  

Can create each raster individually, so this isn't an issue with the input datasets.

**Comment by jblindsay** [comment] 2022-01-04 21:35
I can confirm that the tool works in batch mode when not accessed from the QGIS frontend (i.e. using either the WhiteboxTools Runner, or the Python API) and so I think this issue likely belongs to the Whitebox QGIS frontend instead of here.

**Comment by BrianMoynihan** [comment] 2022-01-04 21:38
Thanks for the prompt response John!  
This happens with a couple other tools as well when run in batch mode, so this sounds like something related to the frontend.

**Comment by jblindsay** [comment] 2022-01-05 01:18
No problem. I'm closing this issue now, but if Alex, over at the QGIS frontend determines that the issue is in fact mine for some reason, then please feel free to re-open.

**Closed by jblindsay** 2022-01-05 01:18 UTC
