### ISSUE TITLE
R's whitebox::wbt_reclass not taking ";" separator on Mac but will take "," on both Windows and Mac 

### ISSUE THREAD

**Issue by bkielstr** [jblindsay/whitebox-tools#154] opened 2021-04-29 19:12 UTC
Hi there,

I have been developing an R package that uses [Reclass](https://jblindsay.github.io/wbt_book/available_tools/gis_analysis.html?highlight=reclass#reclass). In both the User Manual and in the `wbt_reclass()` documentation, the `reclass_vals` calls for a "Reclassification triplet values (new value; from value; to less than), e.g. '0.0;0.0;1.0;1.0;1.0;2.0'."

I have found that in Windows, using "0.0;0.0;1.0;1.0;1.0;2.0" in `whitebox::wbt_reclass()` works.
However in testing the R package using a Mac (on two systems) this did not work. 

Following some playing around and a little bit of luck, I found that "0.0,0.0,1.0,1.0,1.0,2.0" works for both Windows and Mac.  

To fix this, should the Manual/function documentation change or will commas in `reclass_vals` be allowed as input to WhiteboxTools going forward?
  
```
library(whitebox)
library(raster)

whitebox::wbt_init()
whitebox::wbt_version()

workdir <- tempdir()

dem <- system.file("extdata", "DEM.tif", package="whitebox")

## Test functions 
wbt_feature_preserving_smoothing(dem, file.path(workdir, "./smoothed.tif"), filter=9, verbose_mode = TRUE)
wbt_breach_depressions(file.path(workdir, "./smoothed.tif"), file.path(workdir, "./breached.tif"))

## reclass that does not work
wbt_reclass(input = dem, output = file.path(workdir, "reclass.tif"),
            reclass_vals = "1.0;2.0;200.0", assign_mode = FALSE, verbose_mode = TRUE, )

## Error:
## thread 'main' panicked at 'The reclass values string must include triplet values (new value; from value; to less than), e.g. '0.0;0.0;1.0;1.0;1.0;2.0'', src/main.rs:72:21
## note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
## sh: 2.0: command not found
## sh: 200.0: command not found
## Error in system(args2, intern = TRUE) : error in running command

## Reclass that does work 
wbt_reclass(input = dem, output = file.path(workdir, "reclass.tif"),
            reclass_vals = "6000,200,400,5000,500,1000", assign_mode = FALSE, verbose_mode = TRUE, )

plot(raster(dem))
plot(raster(file.path(workdir, "reclass.tif")))
```

Session info for Mac session:

```
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] raster_3.1-5   sp_1.4-2       whitebox_1.4.0

loaded via a namespace (and not attached):
 [1] compiler_4.0.5   assertthat_0.2.1 rgdal_1.5-8      cli_2.0.2       
 [5] tools_4.0.5      glue_1.4.1       rstudioapi_0.11  Rcpp_1.0.4.6    
 [9] crayon_1.3.4     fansi_0.4.1      codetools_0.2-18 grid_4.0.5      
[13] rlang_0.4.10     lattice_0.20-41 
```

**Comment by giswqs** [comment] 2021-04-29 19:24
Have you tested it using the WBT command-line backend? If the same issue occurs, then it is related to the WBT backend. Otherwise, this issue should be open on the whiteboxR repository (https://github.com/giswqs/whiteboxR) if this issue only occurs when using the R frontend.

**Comment by bkielstr** [comment] 2021-04-29 19:52
Hi @giswqs (and thanks for making life so easy with `whitebox::`, thanks for taking the time to answer. 

Running on the same Mac - same error message.

B:~ brian$ /Library/Frameworks/R.framework/Versions/4.0/Resources/library/whitebox/WBT/whitebox_tools --run=reclass  --input=/Library/Frameworks/R.framework/Versions/4.0/Resources/library/whitebox/extdata/DEM.tif --output=/var/folders/z9/cqjtj3ln135_79r_4cbpc15c0000gn/T//RtmpUF461y/reclass --reclass_vals=1.0;2.0;200.0
thread 'main' panicked at 'The reclass values string must include triplet values (new value; from value; to less than), e.g. '0.0;0.0;1.0;1.0;1.0;2.0'', src/main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bash: 2.0: command not found
bash: 200.0: command not found

Running with ";" replaced by "," I can confirm that a new file was written to the temporary directory correctly.

B:~ brian$ /Library/Frameworks/R.framework/Versions/4.0/Resources/library/whitebox/WBT/whitebox_tools --run=reclass  --input=/Library/Frameworks/R.framework/Versions/4.0/Resources/library/whitebox/extdata/DEM.tif --output=/var/folders/z9/cqjtj3ln135_79r_4cbpc15c0000gn/T//RtmpUF461y/reclass --reclass_vals=1.0,2.0,200.0

**Comment by jblindsay** [comment] 2021-05-31 11:54
Okay, I think that I've found this error, but I must admit it is a bit of a strange one. I found that if I placed spaces between each of the values in the reclass string, there was a parsing error. This is a simple fix; all I needed to do was to trim the strings (i.e. remove any whitespace) prior to parsing the strings into numerical values. However, what I don't understand is why this would impact Mac and not Windows and why it would be the case with semi-colons and not commas. I should say that I was not able to reproduce this error, but I was not using the R-frontend in testing. Instead I used the WhiteboxTools Runner. I should say that it worked fine on Mac with semicolons using the WhiteboxTools Runner, but with no spaces. Anyhow, I've pushed the change now that deals with the parsing error and it will appear in v.1.5, which will be released either today or tomorrow. Please feel free to re-open if this issue persists even after this change.

**Closed by jblindsay** 2021-05-31 11:54 UTC
