### ISSUE TITLE
Unrecognized ShapeType: 1092069532 in JensonSnapPourPoints

### ISSUE THREAD

**Issue by sweco-sedalh** [jblindsay/whitebox-tools#213] opened 2021-12-13 14:15 UTC
When running JensonSnapPourPoints with the attached shapefile as input I get the following error:

```
thread 'main' panicked at 'Unrecognized ShapeType: 1092069532', whitebox-vector\src\shapefile\geometry.rs:517:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Shapefile: [pour_pts.zip](https://github.com/jblindsay/whitebox-tools/files/7704383/pour_pts.zip)
Streams: [stream.zip](https://github.com/jblindsay/whitebox-tools/files/7704387/stream.zip)

I presume this is because of the shapefile containing some geometry type that WBT cannot handle, however it has worked previously and should just be PointZ, see this screenshot from QGIS:
![image](https://user-images.githubusercontent.com/82082024/145827738-33d3311e-36fa-4e8c-8032-d0eab5a51216.png)

WBT version: `WhiteboxTools v2.0.0 by Dr. John B. Lindsay (c) 2017-2021`

I'm running the tool through the QGIS plugin, see the full log here:

<details>
<summary>Full QGIS processing log</summary>

```
QGIS version: 3.22.1-Białowieża
QGIS code revision: 663dcf8fb9
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.0
GEOS version: 3.10.0-CAPI-1.16.0
PROJ version: Rel. 8.2.0, November 1st, 2021
PDAL version: 2.3.0 (git-version: 9f35b7)
Algorithm started at: 2021-12-13T14:20:51
Algorithm 'JensonSnapPourPoints' starting…
Input parameters:
{ 'output' : 'TEMPORARY_OUTPUT', 'pour_pts' : 'C:\\Users\\sedalh\\AppData\\Local\\Temp\\processing_InwjXw\\6e11f9a9b92640029a2e8b173b5fdc20\\pour_pts.shp', 'snap_dist' : 200, 'streams' : 'E:/Systemutveckling/Arbetsmaterial/GIS/Underlag_Raster/haros/89090/stream.tif' }

WhiteboxTools command:
"C:/Program Files/WBT/whitebox_tools.exe" -v --run=JensonSnapPourPoints --pour_pts="C:\Users\sedalh\AppData\Local\Temp\processing_InwjXw\6e11f9a9b92640029a2e8b173b5fdc20\pour_pts.shp" --streams="E:\Systemutveckling\Arbetsmaterial\GIS\Underlag_Raster\haros\89090\stream.tif" --snap_dist=200.0 --output="C:\Users\sedalh\AppData\Local\Temp\processing_InwjXw\b1d8e3306fae41e99428fa53f1d9725f\output.shp"
WhiteboxTools output:
***********************************
* Welcome to JensonSnapPourPoints *
* Powered by WhiteboxTools *
* www.whiteboxgeo.com *
***********************************
Reading data...
thread 'main' panicked at 'Unrecognized ShapeType: 1092069532', whitebox-vector\src\shapefile\geometry.rs:517:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Process returned error code 101
Execution completed in 0.27 seconds
Results:
{'output': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/sedalh/AppData/Local/Temp/processing_InwjXw/b1d8e3306fae41e99428fa53f1d9725f/output.shp
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```
</details>

**Comment by jblindsay** [comment] 2021-12-13 14:34
This seems to be a duplicate of #211 and so I am closing. I'm trying to track down the problem right now. It seems to be somewhere in the WBT Shapefile reader, which I must admit, I'm a bit surprised by. For the moment, I would suggest converting your points file from the PointZ ShapeType to the Point ShapeType and trying that. I'm closing this issue and will continue with the other related one.

**Closed by jblindsay** 2021-12-13 14:34 UTC

**Comment by sweco-sedalh** [comment] 2021-12-13 14:54
Thank you for the quick response, I can confirm that dropping the Z-dimension resolves the issue.
